### ISSUE TITLE
Resources table in readme links are all broken

### ISSUE THREAD

**Issue by coleaeason** [marqeta/marqeta-python#1]
Hello!

All of the links in the Resources table in the README do not work. This is because the links are formatted incorrectly. 

Currently they are formatted like:
```md
[/acceptedcountries](#Accepted-Countries-/acceptedcountries)
```

However they should be like this:
```md
[/acceptedcountries](#accepted-countries-acceptedcountries)
```

You can test this easily by trying to go to this link: https://github.com/marqeta/marqeta-python#Accepted-Countries-/acceptedcountries and seeing that it does not take you the section anchor. 

However this link does: https://github.com/marqeta/marqeta-python#accepted-countries-acceptedcountries

Could you please fix the table? Or provide contribution instructions and I will submit a PR?

**Comment by jmoschou-mq** [comment]
Hi @coleaeason, thanks for finding this! I've merged the fix.

**Comment by coleaeason** [comment]
Thanks for the quick fix!
